### ISSUE TITLE
v1.1 crashes

### ISSUE THREAD

**Issue by nihalanand697** [Alaory/WallMe-Wallpaper#4]
updated to the v1.1 but the app is crashing when I open it. Tried a reinstall as well.
Device is Redmi note 11 running on Lineage os android 12.1
this is the crash log
`FATAL EXCEPTION: main
Process: com.alaory.wallmewallpaper, PID: 8097
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alaory.wallmewallpaper/com.alaory.wallmewallpaper.MainActivity}: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.alaory.wallmewallpaper/databases/Image_info.dp
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.alaory.wallmewallpaper/databases/Image_info.dp
	at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:58)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:587)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:422)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:340)
	at com.alaory.wallmewallpaper.database.update_image_info_list_from_database(database.kt:81)
	at com.alaory.wallmewallpaper.MainActivity.onCreate(MainActivity.kt:132)
	at android.app.Activity.performCreate(Activity.java:8057)
	at android.app.Activity.performCreate(Activity.java:8037)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1347)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
	... 12 more`

**Comment by Alaory** [comment]
i already fixed the issue in the 1.2v version

**Comment by nihalanand697** [comment]
> 

Thanks a ton <3
